### ISSUE TITLE
Adicionar empresa que Usa Flutter

### ISSUE THREAD

**Issue by jeffotoni** [FlutterComunidadeBR/empresas-que-usam-flutter-no-brasil#38]
Pessoal mais empresas que usam Flutter
https://s3wf.com.br
http://placecomunicacao.com.br

Nome                           | Cidade                 | Tecnologias Relacionadas | Declaração
s3wf Soluções Web        Belo Horizonte                  Flutter                           --
PlaceComunicação        Belo Horizonte                  Flutter                            --

**Comment by JHBitencourt** [comment]
Olá @jeffotoni.

Você pode criar um PR e adicionar as informações dessas empresas na lista.
Para isso basta seguir as regras de contribuição em [CONTRIBUTING.md](https://github.com/FlutterComunidadeBR/empresas-que-usam-flutter-no-brasil/blob/master/CONTRIBUTING.md).

**Comment by JHBitencourt** [comment]
Estou fechando a issue.
Novas empresas devem ser enviadas via PR.
